# One-time setup: registers the tunnel proxy supervisor to auto-start at
# every user logon by dropping a .vbs launcher into the Windows Startup
# folder. Run this script once after cloning the repo on a new machine.
#
# Usage (no admin required):
#   powershell -NoProfile -ExecutionPolicy Bypass -File scripts\setup-autostart.ps1
#
# To uninstall: delete `ParaSFX-TunnelProxy.vbs` from your Startup folder.

$ErrorActionPreference = 'Stop'

$projectRoot = Split-Path -Parent $PSScriptRoot
$supervisor  = Join-Path $projectRoot 'scripts\run-tunnel-proxy-supervised.ps1'
$startupDir  = [Environment]::GetFolderPath('Startup')
$vbsPath     = Join-Path $startupDir 'ParaSFX-TunnelProxy.vbs'

if (-not (Test-Path $supervisor)) {
    throw "Supervisor script not found at: $supervisor"
}

# Build the .vbs content. Doing this from a template (rather than committing
# the .vbs file) avoids hardcoding any user's project path into the repo.
$vbs = @"
' Auto-start the Para SFX Library tunnel proxy supervisor at user logon.
' Generated by scripts\setup-autostart.ps1 - do not edit by hand.
' To remove auto-start: delete this file.
'
' Logs (in project root):
'   tunnel-proxy.log            - proxy itself
'   tunnel-proxy-supervisor.log - supervisor (restarts proxy if it dies)

Set shell = CreateObject("WScript.Shell")
shell.Run "powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File ""$supervisor""", 0, False
"@

Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII

Write-Host "[OK] Auto-start installed." -ForegroundColor Green
Write-Host ""
Write-Host "  Launcher:  $vbsPath" -ForegroundColor Gray
Write-Host "  Supervisor: $supervisor" -ForegroundColor Gray
Write-Host ""
Write-Host "Will auto-start at the next user logon." -ForegroundColor Cyan
Write-Host "To start it now without rebooting, run:" -ForegroundColor Cyan
Write-Host "    wscript.exe `"$vbsPath`"" -ForegroundColor Yellow
